services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ../frontend/src
          target: /frontend/src
          ignore:
            - node_modules/
            - .git/
        - action: rebuild
          path: ../frontend/package.json

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:2213Tb@db:5432/mydatabase
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /backend/src
          ignore:
            - node_modules/
            - .git/
        - action: rebuild
          path: package.json
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2213Tb
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge